present:
    uvx clippt presentation.toml --continue --disable-footer

textual-console:
    uvx --from textual-dev textual console -x EVENT -x SYSTEM -x DEBUG

dev:
    uv run --with textual-dev --with-editable ../../clippt textual run --dev -c clippt presentation.toml --continue

qr:
    qrencode -t utf8i https://github.com/janpipek/talks/ostrava-python-pizza_2026

clean:
    rm -f chmix/pyproject.toml
    rm -rf chmix/__pycache__

docker-build:
    docker build -t uv-demo docker/

docker-start:
    docker run -dit --name uv-demo --hostname a-completely-different-computer uv-demo

docker-connect:
    docker exec -it uv-demo bash

docker-stop:
    docker stop uv-demo && docker rm uv-demo
